### ISSUE TITLE
Omdraaien kleuren in staafdiagram meerdere staven bij rapport Rotterdam

### ISSUE THREAD

**Issue by SarahBoer** [ggdatascience/gmjv-landelijk-format#101]
Hoi,

Ik loop tegen weer iets bijzonders aan. Als ik het rapport voor Rotterdam uitdraai (gemeentecode= 599) dan worden de kleuren in de staafdiagrammen met meerdere staven omgedraaid. In de de bollen met cijfers gebeurt dit niet. En bij de twee andere gemeenten waarvoor ik een rapport uitdraai gebeurt het ook niet. 

![Schermafbeelding 2024-12-10 162255](https://github.com/user-attachments/assets/901c4688-6051-44bf-b044-d76aaa2cfb73)
tachments/assets/f4cb68cb-c55a-483f-9309-1979649f762e)

**Comment by pieterseinen** [comment]
Kan je de code voor deze grafiek delen?

**Comment by SarahBoer** [comment]
Voorbeeld 1) 

```{r Woonsituatie, fig.alt=ggplot2::get_alt_text(plot)}

# Labels aanpassen
var_label(monitor_df$AGHHA401) <- 'Bij ouder(s)/verzorger(s)'
var_label(monitor_df$AGHHA405) <- 'Met anderen'
var_label(monitor_df$AGHHA406) <- 'Met partner zonder kinderen'
var_label(monitor_df$AGHHA404) <- 'Alleen'

plot <- monitor_df %>%
   maak_staafdiagram_meerdere_staven(
     var_inhoud = c("AGHHA401", "AGHHA405", "AGHHA406", "AGHHA404"),
     var_inhoud_waarde = 1,
     titel = "Woonsituatie",
     niveaus = c("gemeente", "regio"),
     max_as = 115,
     flip = T)

plot

```
Voorbeeld 2)

```{r Werksituatie 6, fig.alt=ggplot2::get_alt_text(plot)}
plot = monitor_df %>% 
  maak_staafdiagram_meerdere_staven(
    var_inhoud = c("FIIKA401", "FIIKA402", "FIIKA403"),
    titel = "Financiële problemen",
    niveaus = c("gemeente", "regio"),
    var_inhoud_waarde =  1
  )

plot

**Comment by pieterseinen** [comment]
Bedankt! Ik heb zojuist een update aan hulpfuncties.R gedaan. Zou je dat bestand kunnen downloaden, het instellingen blok opnieuw willen draaien & kijken of het probleem is opgelost?

De oorzaak was dat de grafiekfunctie de kleur voor regio's gemeente alfabetisch op kleur indeelde. Dat is natuurlijk niet de bedoeling. Dit is bij testen niet opgevallen omdat er niet zo veel gemeenten zijn die alfabetisch achter regio komen.
