### ISSUE TITLE
Percentage lage n wordt niet weggestreept in figuur

### ISSUE THREAD

**Issue by SarahBoer** [ggdatascience/gmjv-landelijk-format#106]
Hoi,

Bij het vervangen van de regio door Rotterdam, wordt bij weergave van een sterretje (wegens lage n) het percentage niet weggestreept.
Ik voeg de code en prtscrn bij. Gebeurt alleen hier. 

plot = monitor_df %>% 
  maak_staafdiagram_uitsplitsing_naast_elkaar(
    var_inhoud = "DIGOA411",
    var_crossings = c("AGGSA402","AGLFA401"),
    kleuren_per_crossing = TRUE,
    fade_kleuren = TRUE,
    flip = TRUE, 
    titel = "Geldproblemen door online gokken laatste jaar (Rotterdam)",
    kleuren = c("#99CCA0","#00811F","#004C31","#008F38", "#62A72B", "#99CCA0", "#00811f", "#004C31", "#739BD0", "#11265F", "#86848D"),
    niveaus = "gemeente"
  )

plot

![Schermafbeelding 2024-12-18 154219](https://github.com/user-attachments/assets/c8fd7936-354b-4a45-add2-061661f1a67a)

**Comment by pieterseinen** [comment]
Is opgelost met laatste update van hulpfuncties.R

**Comment by SarahBoer** [comment]
Opgelost! dank je.
