### ISSUE TITLE
Bolletjesgrafiek over jezelf mogen zijn als LHBTQI toont % gemeente niet

### ISSUE THREAD

**Issue by SarahBoer** [ggdatascience/gmjv-landelijk-format#107]
En dat komt waarschijnlijk doordat andere antwoordcategorieën van deze variabele leeg is. Maar er wordt wel (net) voldaan aan de eis voor minimale aantallen dus zou wel getoond moeten worden:

![image](https://github.com/user-attachments/assets/21d737e2-d788-4c6b-9496-9038dfb8ce4d)

**Comment by pieterseinen** [comment]
Hoi Sarah, Kan je de code die je in quarto gebruikt voor het bolletje delen? Dan gaan we het uitzoeken.

**Comment by SarahBoer** [comment]
de code:

getallen = c(monitor_df %>% maak_percentage(var_inhoud = 'SERIA411',
                                            niveau = "gemeente",
                                            subset_var = "SERIA404",
                                            subset_val = 1),
             monitor_df %>% maak_percentage(var_inhoud = 'SERIA411',
                                            niveau = "regio",
                                            subset_var = "SERIA404",
                                            subset_val = 1))

**Comment by pieterseinen** [comment]
Hoi Sarah, zou het kunnen dat er niet aan het minimum van `nvar` (aantallen per vraag) wordt voldaan?.
Het percentage wordt berekend o.b.v. een subset waarbij `SERIA404` 1 moet zijn. Als ik het goed zie is het aantal respondenten dat deze vraag heeft beantwoord binnen die subset 22.

**Comment by SarahBoer** [comment]
Oké, dus de subset wordt in dit geval gezien als de "variabele"? Ik ben uitgegaan van het feit dat n=342 deze vragen hebben beantwoord en n=10 dit specifieke antwoord hebben gegeven. Maar dat klopt dus niet begrijp ik? Dat is wel een beetje jammer, want dan blijft dit % bij eigenlijk al onze regiogemeenten onzichtbaar.

**Comment by pieterseinen** [comment]
Ik heb daar inhoudelijk niet echt over te oordelen, maar dat is inderdaad hoe het technisch in elkaar zit. Als jullie twijfelen of dit een correcte hantering is van het "grote N" minimum kan je dat het beste navragen bij GGDGHOR / de landelijke werkgroep. 

De ondergrens van `nvar` wordt gecontroleerd o.b.v. het aantal observaties die meegenomen worden voor de gewogen kruistabel.  Door te subsetten worden er minder observaties in de kruistabel meegenomen. Het percentage wat je zou uitrekenen door te filteren op alleen respondenten waarvoor `SERIA404` waar is, is daarmee gebaseerd op een groep van 22 respondenten. Het script laat daarom geen uitkomsten zien.

Je kan ervoor kiezen de argumenten `subset_var` en `subset_val` niet te gebruiken. Dan krijg je het percentage wat "nooit of soms het gevoel heeft zichzelf te mogen zijn als LHBTQIA+er" uit alle respondenten in die gemeenten (je krijgt dan natuurlijk wel een lager percentage).

Alternatief; Ik heb zojuist een update aan het script gedaan waardoor `maak_percentage()` ook de parameters `nvar` en `ncel` heeft gekregen. Je kan die waarden naar beneden bijstellen om toch een percentage te krijgen voor deze visualisatie. Bijvoorbeeld als je `nvar` op 20 wilt hebben. **Let daarbij dus op dat je goed nagaat of dit voldoet aan de afspraken m.b.t. minimale groepsgrootte.**

Bijvoorbeeld:
```
monitor_df %>% maak_percentage(
   var_inhoud = 'SERIA411',
   niveau = "gemeente",
   subset_var = "SERIA404",
   subset_val = 1,
   nvar = 20
```

**Comment by SarahBoer** [comment]
Dank je wel
