### ISSUE TITLE
Deel titel figuur valt weg

### ISSUE THREAD

**Issue by GGD-SR** [ggdatascience/gmjv-landelijk-format#110]
We hebben de titels van figuren verplaatst zodat deze bij alle figuren onder de figuur staan ('vjust' toegevoegd in hulpfucties bij 'plot.title'. Bij liggende figuren valt een deel van de titel echter weg, en bij vertrouwen in de toekomst valt de hele titel weg. Enig idee hoe we de kolom wat langer kunnen maken zodat de titel er helemaal op komt te staan? Alvast bedankt!!

![46beb557-6b3c-4d0a-b51b-5ea944315f6c](https://github.com/user-attachments/assets/628059a3-204e-4335-8666-56c5cbc74e82)

**Comment by pieterseinen** [comment]
Hoi,

Dit zou je kunnen doen dmv de ggplot2 theme() parameter plot.margin. Met deze instellingen krijg ik de tekst er bijvoorbeeld netjes op als ik rechtsonder bij plots op zoom klik in de Rstudio Viewer. Zie de screenshot onderaan. Bij margin() zijn de parameters op volgorde: top, right, bottom, left.

```
plot + theme(plot.title = element_text(vjust = -60), plot.margin = margin(t = -60, r = 50, b = 120, l = 10))
```
Hiermee kan je het oplossen, maar het (de 1e keer) instellen is best bewerkelijk. Je zult waarschijnlijk wel wat moeten experimenteren met de juiste instellingen voor margin. Bij mij werkte het beste om eerst de margins in te stellen en daarna vjust aan te passen. Controleer de instellingen ook in de rapportage. De marge & vjust kunnen (net als met de lettergrootte) anders uitkomen o.b.v. de context waarin een plot wordt weergeven (heeft met resolutie te maken).


![image](https://github.com/user-attachments/assets/24a3de55-02ea-4fc4-a427-5853b956c99c)
