### ISSUE TITLE
Foutmelding voorbeeldrapport uitdraaien

### ISSUE THREAD

**Issue by PaulienHagedoorn** [ggdatascience/gmjv-landelijk-format#51]
Ik krijg een foutmelding bij het uitdraaien van het voorbeeldrapport.

Het gaat om de laatste stap bij 2.3: "Klik nu bovenaan het scherm op “Render”. R gaat nu de rapportage genereren en zal het opslaan als een html bestand “voorbeeld_rapportage.html” in de werkmap".

![image](https://github.com/user-attachments/assets/c7d5d146-5351-4b64-86b1-9855737a325f)

Ik heb de nieuwste versies van R, R studio en alle packages up to date. 
Uiteindelijk heb ik dit opgelost met: install.packages("openxlsx")

**Comment by pieterseinen** [comment]
Bedankt voor het melden! openxlsx moet opgenomen worden in de lijst libraries. Ga ik aanpassen

**Comment by pieterseinen** [comment]
toegevoegd aan main
