### ISSUE TITLE
Foutmelding bij het berekenen van percentages

### ISSUE THREAD

**Issue by LBeek** [ggdatascience/gmjv-landelijk-format#62]
Ik krijg onderstaande foutmelding bij het berekenen van percentages. Ik heb hier nog niets aan het format of het script aangepast (wel met eigen data). Ook de indicator is niet aangepast.

processing file: voorbeeld_rapportage.qmd
  |..                                        |   4%                                                        

Quitting from lines 224-1 (voorbeeld_rapportage.qmd)
Error in `matrix()`:
! length of 'dimnames' [1] not equal to array extent
Backtrace:
 1. monitor_df %>% ...
 2. global maak_percentage(., var_inhoud = "AGGSA401", value = 2, niveau = "gemeente")
 5. global bereken_kruistabel(...)
 6. base::matrix(...)
                                                                                                                      
Execution halted

**Comment by pieterseinen** [comment]
Bedankt voor het melden. De oorzaak van deze melding is dat het script een lege dataset probeert te verwerken. Dit kan verschillende oorzaken hebben:

De gemeente data heeft geen:
- Non-missing data voor die variabele en dat niveau
- Data waarvan er een gemeentelijke standaardisatiefactor bestaat.

Hoogstwaarschijnlijk heeft de gemeente die je probeert te verwerken geen standaardisatiefactor. Je kan dit nakijken in de data en het script aan de praat krijgen door een gemeente in de frontmatter in te voeren die wel een standaardisatiefactor heeft.

Wij zullen een update maken die ervoor zorgt dat deze foutmelding begrijpelijk wordt.

**Comment by pieterseinen** [comment]
repository is geupdatet zodat je nu nederlandstalige errors krijgt wanneer er een dataset van 0 rijen ontstaat door filters.
