### ISSUE TITLE
Rapportages maken met Chrome buiten werkomgeving

### ISSUE THREAD

**Issue by NathalieKoene** [ggdatascience/gmjv-landelijk-format#70]
Binnen onze werkomgeving hebben we geen Google Chrome, maar Microsoft Edge.
Buiten onze werkomgeving kunnen we wel gebruik maken van Google Chrome en R.

Tijdens de workshop bleek dat Microsoft Edge niet de juiste ondersteuning biedt naar een mooi opgemaakte rapportage in pdf. Wel werd ons verteld dat middels een workaround wel zou moeten kunnen.

Waar in de diverse scripts zou dit aangepast moeten worden?
En wat moet er dan in het script aangepast worden?
Met OneDrive zouden we dan de 'tussenbestanden' op kunnen halen en daarna de laatste stappen van het script kunnen runnen.

**Comment by pieterseinen** [comment]
Je zou daarvoor het script *maak_pdf_rapport_per_gemeente.R* voor kunnen openen.

Je voert dan bovenaan de relevante gemeentecodes in en comment dit stuk dan weg:

```  
  #html omzetten naar pdf
  pagedown::chrome_print(
    input = html_file,
    options = list(preferCSSPageSize = FALSE,
                   printBackground = TRUE,
                   scale = .9,
                   landscape = TRUE,
                   margin = list(
                     top = "0.5in",
                     bottom = "0.5in",
                     left = "0.5in",
                     right = "0.5in"
                   )))
  
  file.remove(glue::glue("gemeenterapport_{gemeentecode}.html"))

```

Eerder in de loop worden html bestanden gemakt. `pagedown::chrome_print()` zet ze om tot een pdf. De html bestanden worden standaard verwijderd dmv `file.remove()`. Beide wil je in eerste instantie dan uitzetten.

Vervolgens kan je dit script & de gemaakte html bestanden overzetten naar de omgeving die chrome, het onderstaande stuk wegcommenten en `pagedown::chrome_print()` weer aanzetten.



```
  #eerst een html maken waarbij expliciet een TOC wordt gegenereerd met render_toc() 
  quarto::quarto_render(
    input = "voorbeeld_rapportage.qmd", # Wijzig dit naar "Rapportage.qmd" als je deze voor meerdere gemeentes wil uitdraaien
    output_format = "html",
    output_file = html_file,
    execute_params = list(
      gemeentecode = gemeentecode,
      regiocode = regiocode,
      is_pdf = TRUE
    ),
    #Metadata aanpassen zodat inhoudsopgave naar body verplaatst wordt
    #Verdwijnt bij chrome_print() maar nodig omdat er anders een vlak leeg wordt gehouden
    #aan de zijkant van de rapportage
    metadata = list(`toc-location` = "body",
                    `toc-title` = "Inhoudsopgave",
                    `toc-float` = "false")
  )
  #Daarna met chrome_print omzetten naar pdf. Deze methode zorgt ervoor dat we
  #CSS niet genegeerd bij renderen naar pdf
  
  #Resulteert standaard in favicon error; fixen door html te injecteren.
  #zie: https://appwrk.com/resolving-favicon-ico-404-errors
  #zie: https://stackoverflow.com/questions/1321878/how-to-prevent-favicon-ico-requests/13416784#13416784
  
  #fix voor favicon error in html bestand toevoegen
  html_lines <- readLines(html_file, warn = F)
  html_lines <- sub('</head>',
                    '<link rel="icon" href="data:,"> \n</head>',
                    html_lines)
  writeLines(html_lines, html_file)
```

**Comment by pieterseinen** [comment]
@NathalieKoene Lost dit het voor jullie op? Dan zal ik het issue sluiten.

**Comment by NathalieKoene** [comment]
Hoi Pieter,

we zijn er nog niet aan toegekomen om het te testen. Sluit het issue maar. Mochten er nog problemen zijn, dan zal ik het laten weten.
