### ISSUE TITLE
standaardisatiefactor_regio

### ISSUE THREAD

**Issue by LilasFahham** [ggdatascience/gmjv-landelijk-format#71]
Hoi hoi,

Ik krijg het volgende bij regel 164 in: Rapportage.qmd

```
> design_land <- survey_design_maken(
+                          strata = 'Stratum_regio', 
+                          gewichten = 'Standaardisatiefactor_regio',
+                          data = monitor_df)
Error in na.weight(data.frame(weights)) : missing values in `weights'
```
**Zouden jullie mij kunnen laten weten of dit ligt bij onze data-bestanden of bij iets anders?**

Bovendien: als de data bestanden van 2022 en 2024 worden samen toegevoegd ik krijg bij veel indicatoren (conflicting value labels):

```
Warning: `AGGSA401` and `AGGSA401` have conflicting value labels.
ℹLabels for these values will be taken from `AGGSA401`.
✖ Values: 3
```
Volgens mij klopt de trendbestand bij ons dus ik vraag me af of dit prima is?

Alvast bedankt!

**Comment by pieterseinen** [comment]
De eerste error lijkt er op te wijzen dat er missing waarden zijn in *"Standaardisatiefactor_regio"* Ik zou dus zeggen dat het aan de data ligt. Wat je nog kan doen om het uit te sluiten is de oorspronkelijke `survey` functie draaien. Onze functie is een 'wrapper' voor een functie uit de survey library `svydesign()`. 

Krijg je hierbij ook die foutmelding? 

```
  svydesign(ids = ~1,
              strata = 'Stratum_regio'
              weights ='Standaardisatiefactor_regio',
              data = monitor_df)  
```

De onderste warning over **AGGSA401** is geen ramp en je script zal gewoon blijven werken. De warning geeft aan dat er verschillen zijn in de **'value labels'** tussen twee datasets en er arbitrair wordt gekozen voor 1 set value labels. Een trendsyntax zou dat glad moeten strijken maar dat is voor deze variabele niet gebeurd. Je kan nakijken wat de value labels zijn voor **AGGSA401** in beide datasets om het op te lossen.

**Comment by LilasFahham** [comment]
Bedankt voor je reactie.

Ja ik krijg ook een foutmelding met 

svydesign(ids = ~1,
              strata = 'Stratum_regio'
              weights ='Standaardisatiefactor_regio',
              data = monitor_df)

Ik check nog de data even. 
Veel dank!

**Comment by hannekeputtenstein** [comment]
Hoi Lilas en Pieter,

Ik was hier begin van de middag ook mee bezig en kreeg dezelfde foutmelding. Wij willen in Drenthe niet vergelijken met 2022, dus ik heb het inlezen van de 2022 data uitgeschakeld. Daarna lijkt het script wel verder te runnen. Misschien dat de fout dus ergens bij de 2022 data of het inlezen ervan zit?

**Comment by MFlapper** [comment]
Hoi Pieter,

Wij krijgen dezelfde foutmelding als bij Lilas. Bij het runnen van het voorbeeld script hebben wij deze foutmelding niet, waar we ook dezelfde datasets gebruiken. Kan het te maken hebben met dat er een filter voor ontbrekende weegfactoren niet aan staat? 

Groeten Susan en Marieke

**Comment by pieterseinen** [comment]
De oorzaak van de error is inderdaad het feit dat er in 2022 missing weegfactoren zijn op regioniveau i.c.m. het feit die missings niet worden verwijderd voordat een survey design wordt aangemaakt. 

Als (tijdelijke) oplossing zou de code die `design_land` aanmaakt als volgt aangepast kunnen worden. Alle observaties zonder weegfactor worden dan weggefilterd voordat er een survey design wordt aangemaakt.

```
design_land <- survey_design_maken(
                         strata = 'Stratum_regio', 
                         gewichten = 'Standaardisatiefactor_regio',
                         data = monitor_df %>% filter(!is.na(Standaardisatiefactor_regio)))
```

Ik hoor graag of dit een goede oplossing is en laat dit issue voorlopig nog even open staan. Als het tegenvalt kan @SvdS-LN hier nog naar kijken. Die heeft de meeste ervaring van het inlezen van de data maar kan vanaf volgende week pas reageren.

Zodra ik heb afgestemd zullen we de bovenstaande aanpassing (o.i.d.) ook updaten in de repository.

**Comment by MFlapper** [comment]
Ah bedankt, het werkt nu bij ons met het filter toegevoegd!

**Comment by MFlapper** [comment]
> Ah bedankt, het werkt nu bij ons met het filter toegevoegd!

Toch nog een toevoeging:  met het filter erop staat het volgende in de gemeenrapportages vermeld: [1] "Aantal deelnemers in regio is niet hetzelfde in beide bestanden, check data."

**Comment by LilasFahham** [comment]
Het is ook gelukt en ook met "Aantal deelnemers in regio is niet hetzelfde in beide bestanden, check data." in het rapportage.

**Comment by pieterseinen** [comment]
> Het is ook gelukt en ook met "Aantal deelnemers in regio is niet hetzelfde in beide bestanden, check data." in het rapportage.

Bedankt voor de aanvulling. Ik ga die melding even aanpassen naar een warning zodat je de melding wel krijgt, maar die ook uit kan zetten :)

**Comment by LilasFahham** [comment]
Laatste note: 
Er komt geen vergelijking in de rapportages tussen 2022 en 2024. 
Ik weet het niet of dat is de consequentie van dat 'warning' of iets anders.
Ik check nog verder. 
Veel dank.

**Comment by SvdS-LN** [comment]
De oplossing die Pieter aandraagt, lost praktisch mogelijk het probleem op maar is theoretisch niet juist. Er zouden namelijk geen deelnemers in de datasets moeten zitten zonder Standaardisatiefactor_regio. Die zijn er in de opschoonsyntaxen uit gehaald.

Het probleem is dat er verschillende namen gebruikt worden voor de regionale/landelijke standaardisatiefactor. In 2022 werd deze Standaardisatiefactor genoemd, in 2024 Standaardisatiefactor_regio (omdat er in 2024 ook een Standaardisatiefactor_gemeente is). Voorheen werd dit opgelost door in het script Standaardisatiefactor in de data van 2022 te hernoemen naar Standaardisatiefactor_regio. Nu wordt dit in de trendsyntax gedaan.

**OPLOSSING**
Om dit op te lossen, moet je verschillende dingen controleren.
1.	Check regionale/landelijke standaardisatiefactor in data

Check in alle databestanden hoe de regionale/landelijke standaardisatiefactor heet.
In 2024 zou deze Standaardisatiefactor_regio moeten heten.
In 2022 zou deze Standaardidatiefactor moeten heten, tenzij je de trendsyntax over het bestand gerund hebt. Dan zou deze Standaardisatiefactor_regio moeten heten.

Alleen als de regionale/landelijke standaardisatiefactor nog Standaardisatiefactor heet, moet deze hernoemd worden in het R-script. Dit wordt gedaan door de functie rename(). Dit kun je zo doen:
Voor het lokale/regionale databestand 2022:  
- ga naar regel 108 en 109 in Rapportage.qmd (en/of 122 en 123 in voorbeeld_rapportage.qmd)
- zorg er voor dat hier de volgende code staat:

```
rename(Standaardisatiefactor_regio = Standaardisatiefactor, # Deze regel weghalen als je trendsyntax gerund hebt
      Stratum_regio = Stratum) %>% # Deze regel weghalen als je trendsyntax gerund hebt
```
Voor het landelijke/totale databestand van 2022:
- ga naar regel 117 en 118 in Rapportage.qmd (en/of 131 en 132 in voorbeeld_rapportage.qmd)
- zorg er voor dat hier de volgende code staat:

```
rename(Standaardisatiefactor_regio = Standaardisatiefactor, # Deze regel weghalen als je trendsyntax gerund hebt
      Stratum_regio = Stratum) %>% # Deze regel weghalen als je trendsyntax gerund hebt
```

3.	Check of juiste databestanden ingeladen worden

Vervolgens kun je checken of de juiste databestanden gebruikt worden. 
Voor het lokale/regionale bestand van 2022 en 2024: 
- ga naar de frontmatter in Rapportage.qmd, regel 19 en 21 (en/of 20 en 22 in voorbeeld_rapportage.qmd)
- check bij naam_monitor_data_202(...) het juiste bestand genoemd staat, pas dit anders aan.

Voor het landelijke/totale databestand van 2022 en 2024:
- ga naar regel 73 en 115 in Rapportage.qmd (en/of regel 87 en 129 in voorbeeld_rapportage.qmd) 
- check of hier de juiste naam voor het landelijke/totale databestand gebruikt wordt, pas dit anders aan. Als je bijvoorbeeld de trendsyntax gerund hebt over het landelijke bestand en dit trendbestand onder een andere naam opgeslagen hebt, dan moet je dit aanpassen in regel 115.

4.	Check of juiste padnamen gebruikt worden

Als laatste kun je voor de zekerheid checken of de juiste padnamen gebruikt worden.
Vervolgens kun je checken of de juiste databestanden gebruikt worden. 
Voor het lokale/regionale bestand van 2022 en 2024: 
- ga naar de frontmatter in Rapportage.qmd, regel 18 en 20 (en/of 19 en 21 in voorbeeld_rapportage.qmd)
- check bij path_monitor_data_202(...) de juiste padnaam genoemd staat, pas dit anders aan.

Voor het landelijke/totale databestand van 2022 en 2024:
- ga naar regel 73 en 115 in Rapportage.qmd (en/of regel 87 en 129 in voorbeeld_rapportage.qmd) 
- check of hier de juiste pad naam voor het landelijke/totale databestand gebruikt wordt, pas dit anders aan.
