### ISSUE TITLE
Slaap & LHBTQIA+ ontbrekende cijfers

### ISSUE THREAD

**Issue by GwendaDOTqmd** [ggdatascience/gmjv-landelijk-format#72]
Hoi Sjanne en Pieter,

Voor Slaap en LHBTQIA+ is er in de rapportage wel tekst, maar missen de cijfers.

Groetjes,
Gwenda

**Comment by GGD-SR** [comment]
Hoi! Hier is hetzelfde aan de hand, niet alleen bij slaap een LHBTQIA+. De functie 'bol_met_cijfer' lijkt steeds niet goed te gaan. 

Het zou handig zijn als we een voorbeeld hebben hoe de rapportage eruit ziet als het helemaal goed loopt. Is het mogelijk dat ook te delen.

**Comment by SvdS-LN** [comment]
Hoi Gwenda en Suzan,

Zouden jullie een screenshot kunnen maken van hoe de percentages eruit zien? Bij mij gaat het goed namelijk, dus ik weet niet zeker wat het probleem is. Het kan zijn dat jullie een oudere versie van het format gebruiken (van ~twee weken geleden), daarna zijn nog wat updates gedaan om de iconen goed te laten staan. Dit heeft ook invloed gehad op de bolletjes. Hieronder leg ik uit hoe je handig alle documenten opnieuw kan downloaden en tevens je eigen, al aangepaste rapportage kan bewaren. Heb je nog niks aangepast, dan kun je gewoon het format in een keer opnieuw downloaden. (Deze info staat ook in de bijlage van de mail van GGD GHOR NL op 15-10).

Een voorbeeld van hoe de bolletjes eruit zouden moeten zien:
![image](https://github.com/user-attachments/assets/f7d1cf8b-bfec-4cc6-9f82-b4624d85b6c3)

Hier volgt uitleg hoe je handig alle documenten kunt downloaden én je eigen (al aangepaste) rapportage kan behouden:
-	Geef je rapportage een nieuwe naam, bv. Rapportage_aangepast.qmd.
o	Als je de rapportage opent in R, kun je een nieuwe naam geven via File > Save as 
-	Verplaats je rapportage (met nieuwe naam) naar buiten de map met de andere documenten van het format.
-	Ga naar de Github pagina (https://github.com/ggdatascience/gmjv-landelijk-format) en download alle documenten opnieuw.
-	Plaats de rapportage (met nieuwe naam) in de map met de net gedownloade documenten.
-	Je kunt nu je rapportage renderen (met de geüpdatete onderliggende documenten).


Groeten,
Sjanne

**Comment by GGD-SR** [comment]
Dank Sjanne, 
Hier gaat het nu ook goed.
Groet, Suzan
