### ISSUE TITLE
Fout bij vergelijkingen 3 groepen

### ISSUE THREAD

**Issue by GGD-SR** [ggdatascience/gmjv-landelijk-format#73]
Hoi!

Bij een vergelijking van 3 groepen (bijv. leeftijd) lijkt iets niet goed te gaan in de functie 'maak_vergelijking'. 

Script:
`r monitor_df %>% maak_vergelijking(var_inhoud = 'FIIKA401', variabele_label = 'moeite heeft om alles te betalen wat moet', var_crossing = 'AGLFA401', niveau = "regio")` `r monitor_df %>% maak_vergelijking(var_inhoud = 'FIIKA401', variabele_label = 'moeite heeft om alles te betalen wat moet', var_crossing = 'AGOJB401', niveau = "regio")`

Rapportage:
In de regio is het percentage dat moeite heeft om alles te betalen wat moet onder 18-20 jarigen (26%) **hoger dan en onder** 21-25 jarigen (28%) hoger dan dat van 16-17 jarigen (17%).

Groet, Suzan

**Comment by SvdS-LN** [comment]
Hallo Suzan, 

Dit is geen fout in het script, deze output is bewust zo gemaakt.
Stel: een percentage is onder 18-20 jarigen lager dan onder 16-17 jarigen, maar onder 21-25 jarigen hoger dan onder 16-17 jarigen. Dan wil je wel dat de woorden 'lager dan' en 'hoger dan' erbij gezet worden, anders klopt de tekst niet meer.
In het voorbeeld dat je geeft zou het misschien wel wenselijk zijn om de eerste 'hoger dan' weg te halen. Het script wordt echter erg complex als het voor elke situatie iets anders moet printen.

Mocht je deze tekst anders willen formuleren in je rapportage, dan kun je in Rapportage.qmd het stuk script dat je in je issue noemt vervangen door een stuk tekst.

Groeten,
Sjanne

**Comment by LilasFahham** [comment]
hallo Suzan, 
Zou je mij kunnen laten weten hoe je de tekst hier hebt aangepast ? 
Alvast bedankt.

Groeten,
Lilas 
GGD Groningen
