### ISSUE TITLE
Maak_pdf_rapport_per_gemeente: error: object 'regiocode' not found 

### ISSUE THREAD

**Issue by SarahBoer** [ggdatascience/gmjv-landelijk-format#75]
Bij het runnen van dit script krijg ik de foutmelding dat het object "regiocode" niet wordt gevonden. Een enkelvoudig testrapport maken met "Rapportage.qmd" ging goed. Ik heb de verwijzing bij 'input' aangepast naar de versie van "Rapportage.qmd" waarin ik de juiste regiocode, gemeentenaam en padnamen heb opgenomen.   

#eerst een html maken waarbij expliciet een TOC wordt gegenereerd met render_toc() 
  quarto::quarto_render(
    input = "Testrapport GM JV 2024 Rotterdam def script.qmd", # Wijzig dit naar "Rapportage.qmd" als je deze voor meerdere gemeentes wil uitdraaien
    output_format = "html",
    output_file = html_file,
    execute_params = list(
      gemeentecode = gemeentecode,
      regiocode = regiocode,
      is_pdf = TRUE
    ),

**Comment by pieterseinen** [comment]
Hallo,

regiocode wordt niet aangemaakt in het script. Dat moet wel gebeuren. We passen het aan.

Je kan dit zelf oplossen door bovenin het script de volgende code toe te voegen, waarbij je het getal 1 vervangt met je werkelijke regiocode. 

`regiocode <- 1`

**Comment by SarahBoer** [comment]
Oké, dank je wel!
