### ISSUE TITLE
Aantallen deelnemers kloppen niet

### ISSUE THREAD

**Issue by SarahBoer** [ggdatascience/gmjv-landelijk-format#76]
In de inleiding worden aantallen genoemd die niet kloppen. Het lijkt erop dat de aantallen van 2022 en 2024 hier bij elkaar worden opgeteld.

**Comment by pieterseinen** [comment]
Bedankt voor het melden. Er wordt inderdaad niet gefilterd op jaartal. Dat zou wel moeten.

Ik heb dit aangepast in de repository. Je kan ook zelf de wijziging doen. Het gaat om `AGOJB401 == 2024` toevoegen aan filter()


> In totaal hebben `r monitor_df %>% filter(GGDregio == params$regiocode, AGOJB401 == 2024) %>% nrow()` jongvolwassenen uit `r params$regionaam` de vragenlijst ingevuld. Van deze respondenten komen `r monitor_df %>% filter(Gemeentecode == params$gemeentecode, AGOJB401 == 2024) %>% nrow()` jongvolwassenen uit `r monitor_df %>% filter(Gemeentecode == params$gemeentecode) %>% labelled_naar_character("Gemeentecode") %>% unique()`.

**Comment by SarahBoer** [comment]
Dank je wel weer Pieter!
