### ISSUE TITLE
melding: diff of engine output timed out. No source lines will be available.

### ISSUE THREAD

**Issue by SarahBoer** [ggdatascience/gmjv-landelijk-format#78]
Hoi Pieter en Sjanne,

Het was me eerder nog niet opgevallen, maar bij background jobs krijg ik als het rapport klaar is deze melding:
"**diff of engine output timed out. No source lines will be available.**" Ik kan niet goed inschatten hoe kwalijk deze melding is. De melding verschijnt na een aantal meldingen over missing data die volgens mij gewoon onschuldig zijn maar die ik er toch maar even in heb laten staan omdat ze mogelijk bij elkaar horen. 

processing file: Rapportage-Rijnmond.rmarkdown
                                                                                                                      
output file: Rapportage-Rijnmond.knit.md

Warning messages:
1: In bereken_kruistabel(data = data_x, survey_design = design_temp,  :
  Missing data gevonden bij crossing  AGGSA402
2: In bereken_kruistabel(data = data_x, survey_design = design_temp,  :
  Missing data gevonden bij crossing  AGGSA402
3: In bereken_kruistabel(data = data_x, survey_design = design_temp,  :
  Missing data gevonden bij crossing  AGGSA402
4: In bereken_kruistabel(data = data_x, survey_design = design_temp,  :
  Missing data gevonden bij crossing  AGGSA402
5: In bereken_kruistabel(data = data_x, survey_design = design_temp,  :
  Missing data gevonden bij crossing  AGGSA402
6: In bereken_kruistabel(data = data_x, survey_design = design_temp,  :
  Missing data gevonden bij crossing  AGGSA402
7: In bereken_kruistabel(data = data_x, survey_design = design_temp,  :
  Missing data gevonden bij crossing  AGGSA402
8: In bereken_kruistabel(data = data_x, survey_design = design_temp,  :
  Missing data gevonden bij crossing  AGGSA402
9: In bereken_kruistabel(data = data_x, survey_design = design_temp,  :
  Missing data gevonden bij crossing  AGGSA402
WARNING: Warning: diff of engine output timed out. No source lines will be available.
pandoc 
  to: html
  output-file: Rapportage Rijnmond.html
  standalone: true
  embed-resources: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  css:
    - custom.css
  toc: true
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: nl
  title: Rapport Gezondheidsmonitor Jongvolwassenen Maassluis 2024
  author: Sarah Boer
  message: false
  page-layout: full
  toc-title: Inhoud

**Comment by SvdS-LN** [comment]
Hoi Sarah,

Ik herken deze warning niet, dus heb 'm even nagezocht. De warning heeft te maken met het volgende. Om goed te begrijpen waar errors zitten, wordt op de achtergrond door R bijgehouden op welke regel de error zit. Bij sommige packages is het moeilijker om dit bij te houden. Deze error geeft aan dat R niet goed bij kan houden bij welke regel R is, dus als er een error komt, dat het regelnummer misschien niet precies klopt. Dit heeft verder **geen** op je output, dat zou goed moeten gaan.

Voor meer info, zie: https://github.com/quarto-dev/quarto-cli/discussions/1149

Groeten,
Sjanne

**Comment by SarahBoer** [comment]
Ik kon het zelf zo snel niet vinden. Dank je wel voor het uitzoeken, dat stelt gerust.
