### ISSUE TITLE
-% bij ongewogen percentages

### ISSUE THREAD

**Issue by mariellederijk** [ggdatascience/gmjv-landelijk-format#82]
Bij het de ongewogen percentage van Nederlandse afkomst komt geen percentage. Als je dit wel weegt dan komt er wel een percentage. Dit geldt ook voor ongewogen cijfers van bijvoorbeeld opleiding, maar niet voor leeftijd. Ik zie in het script wel het stuk waar voorwaarden staan wanneer er -% komt te staan, maar weet zo 123 niet wat ik aan moet passen.

![image](https://github.com/user-attachments/assets/8a52409b-92ee-471b-81c4-531e3b632337)

**Comment by SvdS-LN** [comment]
Hoi Mariëlle,

Weet je zeker dat de groep waar het over gaat, groter is dan 100 mensen? In dit voorbeeld zou het wel logisch zijn als dat zo is.. 

Groeten,
Sjanne

**Comment by mariellederijk** [comment]
Hoi Sjanne, 

Ja, aantallen zijn voldoende gaat om een grote gemeente en ik heb de volgende code 'maak_percentage(monitor_df, var_inhoud = 'AGETS411', value = 1, niveau = "gemeente", ongewogen = T)' zowel ongewogen als gewogen gerund. Bij gewogen krijg je wel een percentage.

Groetjes, 
Marielle

**Comment by mariellederijk** [comment]
Hoi Pieter, 

Ik heb/had het nieuwste script hulpfuncties en Rapportage gebruikt. Helaas nog steeds -%.
Kan het iets zijn met de check met missings oid?  Bij leeftijd (geen missings) geeft hij namelijk wel een percentage, maar bij Nederlandse afkomst (wel missings) niet. Alhoewel als het iets met missings zou zijn dan zou er ook geen percentage moeten komen als er wel gewogen wordt.

**Comment by pieterseinen** [comment]
Hoi Mariëlle,

Ik heb zojuist een update gedaan waardoor het probleem opgelost zou moeten zijn. Ging inderdaad nog steeds iets fout in de functie!

**Comment by Lboutalab** [comment]
Hoi Pieter, bij mij werkt het niet. Heb het idee dat R bij mij de 'ongewogen = T' niet herkent of leest, zelfs na het opnieuw downloaden van de hulpfuncties. Cijfers worden nog gewogen meegenomen. En als ik bij andere functies ongewogen cijfers wil meenemen en 'ongewogen = T' toevoeg, krijg ik een foutmelding.

**Comment by pieterseinen** [comment]
@Lboutalab het argument **ongewogen** bestaat alleen voor de functie `maak_percentage()` dus het klopt dat dit niet werkt voor andere functies (de melding "unused argument" zegt dat je een argument hebt ingevoerd wat niet bestaat in die functie). Die optie zou m.i. goed ingebouwd kunnen worden maar dat staat niet op onze planning.

m.b.t. het nog steeds niet functioneren van `maak_percentage`:

Kan het zijn dat het bestand *hulpfuncties.R* niet opnieuw is ingeladen in je R sessie? Op R. 67 van *Rapportage.qmd* staat `source(params$path_hulpfuncties)`, met dit stukje script worden de hulpfuncties geladen. In de frontmatter (stuk bovenaan tussen de '---') is de locatie van het bestand gedefinieerd met de paramter `path_hulpfuncties`. Je zou het volgende kunnen  doen:

- Nieuwe R-sessie starten zodat alles wat ingelezen wordt zeker weten nieuw is. (Session -> New Session)
- De locatie van `path_hulpfuncties` controleren
- Het eerste codeblock draaien waar de data geladen wordt & `source(params$path_hulpfuncties)` staat.

**Comment by mariellederijk** [comment]
Hoi Pieter, 

Bij mij werkt het wel na de update, dankje!

**Comment by pieterseinen** [comment]
Dankjewel, dan weet ik waar ik moet zoeken. Mijn eerste ingeving is dat het gaat om een verschil in de manier (of het moment) van afronden. Dat moet niet gebeuren dus we gaan het oplossen!

**Comment by Lboutalab** [comment]
Hoi Sjanne, de cijfers zijn jammer genoeg niet veranderd. Wordt nog hetzelfde aangegeven als voorheen.

**Comment by SvdS-LN** [comment]
Hallo @Lboutalab,

Helaas. Gaat het ook niet goed als je eerst een nieuwe R-sessie start en daarna het script opnieuw runt/rendert (Session -> New Session)?

Als het dan nog niet werkt, zou je me dan het aantal vrouwen en totaal aantal deelnemers van deze gemeente door willen geven? dan kan ik met die specifieke aantallen testen waar dit mis gaat. In de data van mijn GGD en de voorbeelddata ben ik dit issue namelijk nog niet tegen gekomen.

Groeten,
Sjanne

**Comment by Lboutalab** [comment]
Hoi Sjanne, helaas lukt het met een nieuwe sessie ook niet. De aantallen staan in de eerdere afbeelding die ik heb gestuurd goed dus 41% man, 58% vrouw en 1% anders dan man of vrouw. Dit geldt voor de Gemeente Almere. Maar bij de andere Gemeenten klopt het ook niet helemaal of worden er geen cijfers uitgedraaid. Wij denken er nu aan, in verband met andere ideeën, om aparte scripts te maken en het eventueel handmatig aan te passen.

**Comment by SvdS-LN** [comment]
Hoi @Lboutalab,

Ik bedoel de echt aantallen, niet de percentages. Dus hoeveel jongvolwassenen hebben meegedaan in deze regio en hoeveel vrouwen?

**Comment by Lboutalab** [comment]
Sorry te snel gekeken!
Totale aantal respondenten die hebben meegedaan binnen Flevoland : 3745. 
Totaal aantal respondenten in de Gemeente Almere: 1265
Waarvan vrouw: 734
Waarvan man: 514
Waarvan anders dan man of vrouw: 17.

**Comment by SvdS-LN** [comment]
Hallo @Lboutalab,

Ik heb net de hulpfuncties geüpdatet, er bleek een filter op jaar te ontbreken bij maak_percentage.
Bij mij komen nu de aantallen in de afbeelding overeen met de aantallen in de tekst. Zou je een nieuwe sessie willen starten en de nieuwe versie van de hulpfunctie willen downloaden, en willen doorgeven of je daarmee de juiste (zelfde) percentages uit krijgt?

Groeten,
Sjanne

**Comment by SvdS-LN** [comment]
Super! Dank voor het aangeven, zodat we deze konden oplossen :)
