### ISSUE TITLE
Uitlijning headers met twee regels (en icoontjes)

### ISSUE THREAD

**Issue by SBorsboom** [ggdatascience/gmjv-landelijk-format#83]
In de paragraaf met achtergrondkenmerken willen wij de ongewogen percentages naar geslacht en leeftijd weergeven. Hoe kunnen we dat in het script zetten? Ik heb iets geprobeerd met ongewogen=T, maar dat werkt niet.

Verder hebben we geprobeerd om de titel van beschermende factoren en vertrouwen in de toekomst aan te passen (deel valt nu onder icoontje), maar dat lukte ook niet. 
Heeft iemand een tip?

**Comment by pieterseinen** [comment]
> In de paragraaf met achtergrondkenmerken willen wij de ongewogen percentages naar geslacht en leeftijd weergeven. Hoe kunnen we dat in het script zetten? Ik heb iets geprobeerd met ongewogen=T, maar dat werkt niet.

We zullen dit zsm nakijken. Kan je in de tussentijd toelichten op welke manier het niet werkt? Krijg je bijvoorbeeld géén resultaat of een resultaat wat niet klopt?

> Verder hebben we geprobeerd om de titel van beschermende factoren en vertrouwen in de toekomst aan te passen (deel valt nu onder icoontje), maar dat lukte ook niet.
Heeft iemand een tip?

Kan je toelichten wat je bedoeld met 'dat lukte niet'? Kan je het niet aanpassen of heeft het niet het gewenste resultaat?
In het eerste geval zou je kunnen nakijken of de editor linksboven ingesteld staat op visual of source. Deze aanpassing kan je het beste in source modus maken.

De kop ziet er in source zo uit;
`# ![](iconen/Vertrouwen_XL.png) Beschermende factoren en vertrouwen in de toekomst {.h1-icoon}`

Je kan het icoontje hier aanpassen `![](iconen/Vertrouwen_XL.png)`. Als je een kop zonder icoontje wilt kan je de hele kop vervangen door: 

`# Nieuwe titel`

**Comment by pieterseinen** [comment]
Over de ongewogen cijfers: 

Op 5 november zijn er issues gefixt m.b.t. de optie `ongewogen = T` Als je scripts ouder zijn dan dat kan je de code opnieuw downloaden (eventueel kan je alleen het script hulpfuncties.R vervangen zodat je de eigen aanpassingen niet verliest).

**Comment by SBorsboom** [comment]
Dank voor de tip mbt nieuwe versie hulpfunties. Ik had gemist dat er iets gewijzigd was. Nu werkt het voor de ongewogen cijfers.

 Wat betreft de titel aanpassen: beschermende factoren en vertrouwen in de toekomst . Deze titel gaat over 2 regels en dat maakt het rommelig. We wilden proberen het woord toekomst uit te lijnen met de regel erboven. Dat lukt niet, ook niet in de source code.

**Comment by pieterseinen** [comment]
Als het goed is zal de kop zonder icoon automatisch uit moeten lijnen. Als je een kop met icoon wilt waarbij de 2e regel ook na het icoon inspringt zouden wij wat aan de css voor `.h1-icoon` moeten aanpassen. 

Daar heb ik niet direct tijd voor maar we zetten het op de lijst.

**Comment by SBorsboom** [comment]
Dank voor de reactie, Dan moeten we voor nu de titel maar aanpassen

**Comment by pieterseinen** [comment]
@SBorsboom ik heb het bestand `custom.css` aangepast zodat alle tekst een stukje naar rechts uitlijnt bij een icoontje. Dus ook titels die 2 regels hebben.
