### ISSUE TITLE
Percentages in vergelijkingen 2022 / 2024

### ISSUE THREAD

**Issue by GGD-SR** [ggdatascience/gmjv-landelijk-format#84]
In de rapportage wordt geregeld een vergelijking gemaakt met 2022. Hierbij wordt weergegeven of het % nu lager, gelijk of hoger is dan in 2022. Tussen haakjes wordt het percentage van 2022 gepresenteerd. Heeft iemand ideeën hoe de functie zo aan te passen dat ook het percentage van 2024 steeds gepresenteerd wordt, zodat direct duidelijk is hoeveel hoger/lager een percentage is t.o.v. 2022?

**Comment by pieterseinen** [comment]
Het gaat hier denk ik om de functie `maak_vergelijking()`. Dat zou goed te doen moeten zijn. Ik kan daar niet direct aan beginnen maar we zullen het meenemen.

**Comment by pieterseinen** [comment]
@GGD-SR ik heb aan de functie `maak_vergelijking` een argument toegevoegd `met_percentage_huidig`. Dit staat standaard op FALSE, als je die op TRUE zet krijg je het percentage van het huidige jaar tussen haakjes in de vergelijking.
