### ISSUE TITLE
Grafiek_cbs_bevolking filteert niet op huidig jaar

### ISSUE THREAD

**Issue by edissepo** [ggdatascience/gmjv-landelijk-format#85]
Bij de achtergrondkenmerken is opgevallen dat de percentages van geslacht niet overeenkomen met de grafiek. Zie hieronder

Na enig onderzoek blijkt dat er in de functie "maak_grafiek_cbs_bevolking" niet wordt gefiltreerd op jaar. Dus de resulterende percentages per geslacht zijn die van zowel 2024 als 2022 samen. 

Check misschien even de aanmaak van objecten aantallen_gemeente en aantallen_regio.
bij filter kan je misschien het jaar nog erbij zetten, zoiets
aantallen_gemeente <- data %>% 
    filter(Gemeentecode == gem_code & AGOJB401 == 2024) %>% 
    group_by(!!sym(crossing_monitor)) %>% 
    summarise(aantal = n()) %>%
    rename(crossing = 1) %>% 
    mutate(regio = val_label(data$Gemeentecode,gem_code),
           crossing = replace(crossing, is.na(crossing),missing_label),
           type = "Deelnemers"
    )

![image](https://github.com/user-attachments/assets/4445f4fb-f6ca-48e2-b7ae-b0d96aa9d393)

**Comment by pieterseinen** [comment]
Bedankt voor het melden. Is zojuist opgelost. Zit nu, net als bij andere functies, ook een `jaarvar` en `huidig_jaar` argument in de functie.
