### ISSUE TITLE
Wegvallen deel figuur

### ISSUE THREAD

**Issue by GGD-SR** [ggdatascience/gmjv-landelijk-format#88]
Hoi! Bij sommige figuren (woonsituatie, vertrouwen in de toekomst) valt aan de rechterkant een deel weg. Het is ons nog niet gelukt dit op te lossen. Iemand ideeën? Groet, Suzan

**Comment by pieterseinen** [comment]
Kan je daar een voorbeeld van laten zien?

**Comment by GGD-SR** [comment]
Het gaat om het percentageteken na '88' bij ouders/verzorgers en om de laatste letter (als we naast 'regio' ook de naam van de regio willen toevoegen). 
![image](https://github.com/user-attachments/assets/7bcc539f-0e96-419b-8ef6-792f83bf759a)

**Comment by SBorsboom** [comment]
Wij hebben iets soortgelijks bij de grafiek over vertrouwen in de toekomst. Ik heb geprobeerd om de kolomverdeling aan te passen , maar dat maakte niets uit

![image](https://github.com/user-attachments/assets/ee05a15f-969c-4503-b51d-255572b95370)

**Comment by pieterseinen** [comment]
Dit issue heeft te maken met de grafiek zelf (het ggplot object). De layout van de rest van het document gaat daar inderdaad geen invloed op hebben. De 'plot-area' wordt bepaald door waar de balken/staven ophouden & buiten de plot-area wordt tekst helaas afgeknipt. De oplossing is dus de plot-area groter maken. 

We kunnen het dan mogelijk maken om bij hoge percentages een stuk blanco plot-area toevoegen (door de X-as op 110% in te stellen i.p.v. 100%). 

Ik zou dan voorstellen dit handmatig instelbaar te maken met bv het argument `plot-area`. Dit zal dan standaard op 100 staan, maar kan handmatig opgehoogd worden wanneer er tekst buiten het plot valt. Dit lijkt me handmatig het meest verstandig omdat we dan met beide voorbeelden kunnen omgaan.

NB: m.b.t. tot het tweede plaatje. Het probleem van afknippen van labels zal (afhankelijk van de lengte van labels) altijd tot op zekere hoogte bestaan. Het kan zijn dat je label zo lang is dat de plot-area zo veel groter maken je lay-out verpest. Denk daarom ook aan het al bestaande argument `x_as_label_wrap`. Je kan hier een getal invoeren. Dat is het aantal tekens voordat het script een regeleinde toevoegt. Het woord cijfer zou bij een lagere waarde voor `x_as_label_wrap` dan op de 2e regel verschijnen waardoor het binnen het plot blijft.

**Comment by mariellederijk** [comment]
Het aanpassen van x_as_label_wrap gaf bij mij niet het gewenste resultaat. Ik heb uiteindelijk de volgende aanpassing gedaan: 
![image](https://github.com/user-attachments/assets/a42c47b3-c41d-4736-b4bd-16cffed6995e)
en ik krijg dan dit:
![image](https://github.com/user-attachments/assets/d0743f37-bfd9-4927-ac3b-d89d43c6575d)

**Comment by pieterseinen** [comment]
Goed bedacht! Ga kijken of ik dat kan meenemen als instelbaar argument. Ik laat dit issue nog even open, ook omdat er nog problemen zijn op te lossen met labels bij hoge percentages.

**Comment by pieterseinen** [comment]
Ik heb voor `maak_staafdiagram_meerdere_staven()` en voor `maak_staafdiagram_gestapeld()` het argument `max_as` toegevoegd. Dit staat standaard ingesteld op 101, maar kan aangepast worden. 

Als er categorieën zijn met hele hoge percentages waardoor ze buiten de plot-area vallen kan je deze parameter aanpassen. 
Bijvoorbeeld na kunstmatig de variabele Alleen op 100% zetten valt het percentage buiten de grafiek

```
monitor_df %>%
   maak_staafdiagram_meerdere_staven(
     var_inhoud = c(#"AGHHA401", "AGHHA405", "AGHHA406", #Slechts de variabel ALLEEN testen
                    "AGHHA404"),
     var_inhoud_waarde = 1,
     titel = "Woonsituatie",
     niveaus = c("gemeente", "regio"),
     flip = T)
```
![image](https://github.com/user-attachments/assets/ea9d8926-b45a-4d65-8e63-edb2742dc185)

Door `max_as` op 115 in te stellen valt dit hoge percentage niet weg.

```
monitor_df %>%
   maak_staafdiagram_meerdere_staven(
     var_inhoud = c(#"AGHHA401", "AGHHA405", "AGHHA406", #Slechts de variabel ALLEEN testen
                    "AGHHA404"),
     var_inhoud_waarde = 1,
     titel = "Woonsituatie",
     niveaus = c("gemeente", "regio"),
     flip = T,
     max_as = 115)
```
![image](https://github.com/user-attachments/assets/86951647-1616-46db-b8c0-b4150ed5ad14)

**Comment by pieterseinen** [comment]
Sluiten omdat `max_as` met beide problemen kan omgaan. Legenda naar links opschuiven is een optie maar niet noodzakelijk om in te bouwen.
