### ISSUE TITLE
Leesbare foutmelding bij foutieve kleurcodes ggplot2 (was Script loopt niet meer)

### ISSUE THREAD

**Issue by SBorsboom** [ggdatascience/gmjv-landelijk-format#90]
Vorige week hadden we nog een werkend script. Vandaag heb ik een nieuwe hulpfuntie gedownload en een nieuwe custom.css.
Wanneer ik nu render krijg ik al een foutmelding bij de grafiek bij de grafiek met cbs gegevens. Daarin heb ik niets gewijzigd.
De melding is:

  |..                                        |   6% [Achtergrondkenmerken 3]   Error in `!continue`:
! invalid argument type
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
  9. knitr:::call_block(x)

Als ik het stukje los run krijg ik de melding:
Error in monitor_df %>% maak_grafiek_cbs_bevolking(niveaus = c("gemeente",  : 
  could not find function "%>%"
function (x, y, ...) 
UseMethod("plot")
<bytecode: 0x000002e2f32e97b8>
<environment: namespace:base>
 11. knitr:::block_exec(params)
 12. knitr:::eng_r(options)
 14. knitr (local) evaluate(...)
 15. evaluate::evaluate(...)

Ik heb geprobeerd om deze grafiek even eruit te laten, maar dan krijg ik bij een volgende grafiek een foutmelding.
Ik heb geen idee hoe dit kan aangezien ik verder niets heb aangepast. Waar zou dit aan kunnen liggen?

**Comment by SBorsboom** [comment]
Inmiddels ben ik erachter dat de zgn gestapelde grafieken foutmeldingen opleveren.
Deze komen op meerdere plekken in de rapportage terug, dus ik ben benieuwd hoe ik dit kan oplossen.

**Comment by SvdS-LN** [comment]
Hoi!

In [Achtergrondkenmerken 3] wordt geen gestapelde staafdiagram gemaakt, maar worden meerdere staven naast elkaar getoond met de functie maak_staafdiagram_meerdere_staven(). Tenzij je hier iets in hebt aangepast? Zou je de code in [Achtergrondkenmerken 3] misschien kunnen doorsturen?

De tweede error die je noemt (als je het stukje los runt) komt doordat je niet alle packages ingeladen hebt. Zou je misschien het codeblok [Instellingen] eerst willen runnen en dan het codeblok waar de error komt? En door willen geven welke error je dan krijgt?

Dan kunnen wij beter zien waar het mis gaat.

Groeten,
Sjanne

**Comment by SBorsboom** [comment]
De code van Achergrondkenmerken is:

```{r Achtergrondkenmerken 3, fig.alt=ggplot2::get_alt_text(plot)}
plot = monitor_df %>% maak_grafiek_cbs_bevolking(
   niveaus = c("gemeente", "regio"),
   titel = "Leeftijd"
 )

plot
```
Dit gaf eerder de volgende grafiek: 
![image](https://github.com/user-attachments/assets/0ff49518-c55c-4372-8a83-00e40eac9f63)

Als ik het stukje los run nadat ik de packages heb gerund krijg ik de volgende melding:
Error in `geom_bar()` at hulpfuncties.R:3004:2:
! Problem while converting geom to grob.
ℹ Error occurred in the 1st layer.
Caused by error:
! Invalid hexadecimal digit
Run `rlang::last_trace()` to see where the error occurred.

**Comment by SBorsboom** [comment]
![image](https://github.com/user-attachments/assets/7380ca28-0464-47c7-819c-59eb6ada4d92)

bij mij is het iets meer ben ik bang met wat testrapporten. Inmiddels heb ik ook een map met Rapportages_files gekregen. Wanneer ik nu het script run, krijg ik een melding om die map te verwijderen, maar dat lukt niet omdat deze in gebruik is.
(ConnectionFailure user error (Network.Socket.gai_strerror not supported: 11001))
ERROR: Het proces heeft geen toegang tot het bestand omdat het door een ander
proces wordt gebruikt. (os error 32): remove 'M:/Beleidsadvies en Onderzoek/Vertrouwelijk/Kwantitatief onderzoek/Gezondheidsmonitoren/monitor Jongvolwassenen/2024/Rapportage/gmjv-landelijk-format-main/gmjv-landelijk-format-main/Rapportage_files'
Stack trace:
proces wordt gebruikt. (os error 32): remove 'M:/Beleidsadvies en Onderzoek/Vertrouwelijk/Kwantitatief onderzoek/Gezondheidsmonitoren/monitor Jongvolwassenen/2024/Rapportage/gmjv-landelijk-format-main/gmjv-landelijk-format-main/Rapportage_files'

Dit heb ik allemaal nog nooit eerder gehad. Ik heb diverse grafieken even "uit"gezet om de rest van de rapportgae te zien. Maar dan wordt en heel deel niet gerund.

**Comment by SBorsboom** [comment]
![image](https://github.com/user-attachments/assets/830eb56c-4141-41bc-a586-25d1bbde4491)

Dit waren de laatste files in het rijtje

**Comment by SvdS-LN** [comment]
Zou je willen proberen of dit het oplost:

- Sluit R-studio af
- Open het project opnieuw door te klikken op: 
![image](https://github.com/user-attachments/assets/92f1430f-8890-4813-9756-7e9cb03d70af)
- Verwijder de map Rapportage_files
- Render de rapportage

**Comment by SvdS-LN** [comment]
De map Rapportage_files moet in ieder geval weg, deze gaat anders errors geven. R gebruikt deze map om tijdens het renderen figuren in op te slaan. Normaal gesproken verwijderd R deze map na het renderen. Als je het renderen tussendoor afbreekt door bv. op STOP te drukken, dan blijft deze map bestaan en dat geeft errors.

**Comment by SBorsboom** [comment]
Alles geprobeerd, maar helaas ben ik terug bij dezelfde foutmelding



processing file: Rapportage.qmd
  |...                                          |   6% [Achtergrondkenmerken 3]Error in `!continue`:
! invalid argument type
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
  9. knitr:::call_block(x)
 10. knitr:::block_exec(params)
 11. knitr:::eng_r(options)
 14. knitr (local) evaluate(...)
 15. evaluate::evaluate(...)

Quitting from lines 295-301 [Achtergrondkenmerken 3] (Rapportage.qmd)

**Comment by SBorsboom** [comment]
Er lijkt wat mij betreft wel iets te zijn met gestapelde grafieken, de eerste is met 3 leeftijdsgroepen, 
Ik heb ook grafieken met vertrouwen in de toekomst in 3 groepen, eenzaamheid in 3 gradaties/groepen  en de beoordeling eigen mentale gezondheid (in 3 gradaties/groepen).
Deze kreek ik eerst allemaal gewoon, maar geven nu allemaal een foutmelding. De rest van het script kan ik deels wel runnen

**Comment by pieterseinen** [comment]
Hoi @SBorsboom de error die je krijgt bij het renderen is waarschijnlijk niet informatief. Zie: https://github.com/yihui/knitr/issues/2366

Zou je daarom eerst het 1e codeblock kunnen draaien (waarin alle libraries en data worden gelezen) en vervolgens de losse blokjes die de foutmelding geven?

**Comment by SBorsboom** [comment]
Ik heb het opnieuw geprobeerd en krijg nu de melding:

<html>
<body>

Error in UseMethod("get_alt_text") :    no applicable method for 'get_alt_text' applied to an object of class "function" > plot = monitor_df %>% maak_grafiek_cbs_bevolking( +    niveaus = c("gemeente", "regio"), +    titel = "Leeftijd" +  ) >  > plot Error in `geom_bar()` at hulpfuncties.R:3004:2: ! Problem while converting geom to grob. ℹ Error occurred in the 1st layer. Caused by error: ! Invalid hexadecimal digit Run `rlang::last_trace()` to see where the error occurred.
--

**Comment by pieterseinen** [comment]
Het gaat om de 2e melding "plot Error in geom_bar". Wat zie je als je `rlang::last_trace()` draait na de error?

**Comment by SBorsboom** [comment]
Bedoel je dit:

<html>
<body>

Backtrace:      ▆   1. ├─base (local) `<fn>`(x)   2. └─ggplot2:::print.ggplot(x)   3.   ├─ggplot2::ggplot_gtable(data)   4.   └─ggplot2:::ggplot_gtable.ggplot_built(data)   5.     └─ggplot2:::by_layer(...)   6.       ├─rlang::try_fetch(...)   7.       │ ├─base::tryCatch(...)   8.       │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)   9.       │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])  10.       │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)  11.       │ └─base::withCallingHandlers(...)  12.       └─ggplot2 (local) f(l = layers[[i]], d = data[[i]])  13.         └─l$draw_geom(d, layout)  14.           └─ggplot2 (local) draw_geom(..., self = self)  15.             └─self$geom$draw_layer(...)  16.               └─ggplot2 (local) draw_layer(..., self = self)  17.                 └─base::lapply(...)  18.                   └─ggplot2 (local) FUN(X[[i]], ...)  19.                     ├─rlang::inject(self$draw_panel(data, panel_params, coord, !!!params))  20.                     └─self$draw_panel(data, panel_params, coord, width = NULL, flipped_aes = TRUE)  21.                       └─ggplot2 (local) draw_panel(..., self = self)  22.                         └─ggproto_parent(GeomRect, self)$draw_panel(...)  23.                           └─ggplot2 (local) draw_panel(..., self = self)  24.                             ├─ggplot2:::ggname(...)  25.                             │ └─grid::grobName(grob, prefix)  26.                             ├─grid::rectGrob(...)  27.                             │ └─grid::grob(...)  28.                             ├─grid::gpar(...)  29.                             │ └─grid:::validGP(list(...))  30.                             │   └─grid (local) numnotnull("fontsize")  31.                             └─ggplot2::fill_alpha(coords$fill, coords$alpha)  32.                               └─scales::alpha(fill, alpha)  33.                                 └─farver::decode_colour(colour, alpha = TRUE)  34.                                   └─farver:::decode_c(...) Run rlang::last_trace(drop = FALSE) to see 5 hidden frames.
--

**Comment by SBorsboom** [comment]
Bovenstaande is misschien niet zo duidelijk

![image](https://github.com/user-attachments/assets/482465a4-2322-4c7b-8c17-bf33d2c8b69c)
![image](https://github.com/user-attachments/assets/6f3a9e12-6ba0-43ce-b194-e38c389ae5f6)

**Comment by pieterseinen** [comment]
@SBorsboom het probleem ontstaat waarschijnlijk door een fout in de kleurcodes die ingevoerd worden. Mogelijk staat er een typefout in de definitie van `default_kleuren_grafiek` in de frontmatter.

Je zou deze oorzaak kunnen uitsluiten door de functie ook met een andere kleurvector te draaien bijvoorbeeld:

```
monitor_df %>% maak_grafiek_cbs_bevolking(
  niveaus = c("gemeente", "regio"),
  titel = "Leeftijd",
  kleuren = c("green","red","blue"))
```

Hopelijk lost dit het op. Als dat zo is zou je dus de definitie van `default_kleuren_grafiek` op fouten moeten controleren.

**Comment by SBorsboom** [comment]
Ik ben inderdaad bezig geweest met kleuren uit de eigen huisstijl toe te voegen. Ik heb nu ontdekt dat ik bij een kleur een 'o' ipv een 0 had staan. Dat is dan blijkbaar een kleur die alleen in de gestapelde grafieken gebruikt wordt.
Excuses voor deze verwarring. Je begrijpt nu wel dat ik het hele R en Quarto niet zo goed beheers.

**Comment by pieterseinen** [comment]
Helemaal geen probleem :) Fijn dat het gefixt is. Ik zal dit issue omzetten naar een mogelijke verbetering waarbij we een duidelijk errorbericht kunnen geven.

**Comment by pieterseinen** [comment]
Alle grafiekfuncties zijn nu voorzien van een stap die de kleurcodes valideert. Als er niet-valide kleurcodes ingegeven worden krijg je een leesbare warning.
