### ISSUE TITLE
Indicator LHBTQIA+

### ISSUE THREAD

**Issue by GGD-SR** [ggdatascience/gmjv-landelijk-format#93]
Een figuur heeft als titel 'heeft nooit of soms het gevoel als LHBTQIA+er zichzelf te mogen zijn bij anderen'. Dit percentage is vrij laag. Het lijkt erop dat de referentie het totaal aantal jongvolwassenen betreft ipv alleen die personen die zichzelf als LHBTQIA+ zien.

**Comment by GGD-SR** [comment]
Reactie vanuit GGD/RIVM:
Alle indicatoren worden aangemaakt als percentage van de gehele bevolking, zodat er geen verwarring ontstaat. Dit presenteert het RIVM ook op bijvoorbeeld RIVM StatLine, omdat dat alleen cijfers zijn zonder verdere toelichting. 
Voor andere publicaties zoals een rapportage kan wel een andere keuze worden gemaakt. In dit geval is het inderdaad relevant om het percentage binnen de groep LHBTQIA+ te presenteren. Eventueel kan je ook beide doen: “…% van de LHBTQIA+ers heeft … , dit is …% van de hele groep jongvolwassenen.”
Ons advies zou zijn om daar niet de ruwe variabele voor te gebruiken, maar dan SERIA411 uitdraaien binnen een selectie van LHBTQIA+.

**Comment by pieterseinen** [comment]
Dit is een specifieke wens voor een inhoudelijke wijziging die mogelijk niet gedeeld wordt door andere GGD'en. Daarom zullen we het niet aanpassen in de rapportage op github.

Ik heb de optie om een extra subset variabele in te geven bij de functie `maak_percentage` ingebouwd in het script hulpfuncties (die zou je dus even opnieuw moeten downloaden).

Vervolgens kunnen jullie de argumenten `subset_var` en `subset_val` gebruiken om de wijziging door te voeren zoals hieronder:

```
getallen = c(monitor_df %>% maak_percentage(var_inhoud = 'SERIA411',
                                            niveau = "gemeente",
                                            subset_var = "SERIA404",
                                            subset_val = 1),
             monitor_df %>% maak_percentage(var_inhoud = 'SERIA411',
                                            niveau = "regio",
                                            subset_var = "SERIA404",
                                            subset_val = 1))

getallen %>% 
  bol_met_cijfer(niveau = c("Gemeente", "Regio"),
                 omschrijving = "heeft nooit of soms het gevoel als", 
                 omschrijving2 = "LHBTQIA+er zichzelf te mogen zijn bij anderen.")

```

Als vanuit de GGDGHOR / werkgroep wordt aangegeven dat dit opgenomen moet worden in het standaard rapport zullen we dat alsnog doen.
