### ISSUE TITLE
Kleiner maken logo ZON MW en GGD logo

### ISSUE THREAD

**Issue by SBorsboom** [ggdatascience/gmjv-landelijk-format#94]
Wij hebben naast het logo van ZONMW het eigen GGD logo toegevoegd. 
Nu komen die erg groot in beeld. Is er een manier om dit te verkleinen?

**Comment by SvdS-LN** [comment]
Hallo @SBorsboom,

De grootte van de afbeeldingen kun je aanpassen door deze in een column te zetten en grootte van de column aan te passen. 
Het ZonMw logo staat bijvoorbeeld standaard in een column van 30/(30+70) = 30% van het scherm:

::::: {layout="[30,70]"}
::: column
![](iconen/logo_zonmw.jpg)
:::

::: column
:::
:::::

Als je deze kleiner wil, kun je het getal 30 kleiner maken.

Meer informatie over columns en hoe dit werkt, vind je hier: https://ggdatascience.github.io/gmjv-landelijk-format/tekst-en-layout.html#kolomlayout

Groeten,
Sjanne

**Comment by pieterseinen** [comment]
@SBorsboom nog een toevoeging. Een directere manier om het formaat van afbeeldingen te wijzigen kan je hier vinden terugvinden: https://quarto.org/docs/authoring/figures.html

bijvoorbeeld:

> ![Elephant](elephant.png){width=300}
Maakt een plaatje 300 pixels breed

> ![Elephant](elephant.png){height=50%}
Schaalt een plaatje 50% zodat het 50% de beschikbare hoogte inneemt.

**Comment by SBorsboom** [comment]
Dank, met width werkt heel eenvoudig!
