### ISSUE TITLE
Jaartal als niveau bij staafdiagram dubbele uitsplitsing

### ISSUE THREAD

**Issue by SarahBoer** [ggdatascience/gmjv-landelijk-format#96]
Hoi Pieter en Sjanne,

Ik wil voor de regio een trendgrafiek maken met het aandeel jongeren dat nog bij de ouders woont, uitgesplitst naar leeftijd. Hiervoor dacht ik een staafdiagram met dubbele uitsplitsing te gebruiken maar ik loop tegen een aantal dingen aan:

1. Percentages en staven matchen niet. 
2. Hoge percentages vallen weg en toevoegen van de eerder voorgestelde oplossing (max_as = 115) lijkt geen invloed te hebben. 

In de hulpfuncties lijkt er bovendien een restrictie te zijn ingebouwd die vergelijking van 2022 met 2024 in een dergelijke grafiek onmogelijk maakt:  "huidig_jaar = 2024", maar misschien interpreteer ik dat verkeerd. In elk geval graag jullie advies.

![Schermafbeelding 2024-12-05 103027](https://github.com/user-attachments/assets/bfbef114-8b3d-47e9-b6a5-0dd9c975ce6c)

**Comment by SarahBoer** [comment]
Punt 2 is inmiddels opgelost. Punt 1 nog niet :).

**Comment by SarahBoer** [comment]
Hoi Pieter,

Punt 2 was opgelost (inderdaad door toevoegen van max_as). Punt 1 nog niet, helaas :). Dus als je die zou kunnen oplossen dan zou ik daar heel blij mee zijn.

**Comment by pieterseinen** [comment]
Kan je het door jou gebruikte stukje code sturen?

**Comment by SarahBoer** [comment]
Ik heb zelf de optie max as toegevoegd in hulpfuncties.

**Comment by SarahBoer** [comment]
Werkt prima, dank je!
