### ISSUE TITLE
top 3 anticonceptie labels tonen " (opgeschoond)"

### ISSUE THREAD

**Issue by edissepo** [ggdatascience/gmjv-landelijk-format#97]
Het resulterende rapport toont de labels van de SESEA404 : SESA412 variabelen maar hierin staat nog (opgeschoond) achter. 
Bijv: "welke anticonceptiemethode gebruikte jij of je sekspartner bij de laatste keer vaginale seks? - de pil (opgeschoond)"

Wij hebben deze verwerkt in Rapportage.qmd in het Instellingen blok:

variables_to_update <- c("SESEA404", "SESEA405", "SESEA406", "SESEA407", 
                         "SESEA408", "SESEA409", "SESEA410", "SESEA411", "SESEA412")
for (var in variables_to_update) {
  oude_label <- var_label(monitor_df[[var]])
  nieuwe_label <- str_replace(oude_label, " \\(opgeschoond\\)", "")
  var_label(monitor_df[[var]]) <- nieuwe_label
}

**Comment by pieterseinen** [comment]
Bedankt voor het melden. Dit is eigenlijk een issue met de aanlevering van de data & niet met het rapport. Ik zal eens overleggen op welke plek dit het beste aangepast kan worden en het zonodig in het script doen.
